apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: nov29-oldargocd
  janus-idp.io/tekton: nov29-oldargocd
  backstage.io/kubernetes-id: nov29-oldargocd
  backstage.io/kubernetes-namespace: rhdh-app 
  app.kubernetes.io/part-of: nov29-oldargocd
resources: 
- initialize-namespace.yaml
- deployment-model-server.yaml
- service-model-server.yaml
- deployment.yaml
- route.yaml
- service.yaml
- model-config.yaml
